# .travis.yml
language: go

sudo: false

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

before_install:
  - chmod +x ./.travis.gofmt.sh

script:
  - ./.travis.gofmt.sh
  - go get -d -v -t ./...
  - go test -v -race $(go list ./... | grep -v vendor)
