# .travis.yml
language: go

services:
  - docker

sudo: false

# Test for different go environemets
go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

script:
  - ./.travis.gofmt.sh

after_script:
  - chmod +x ./.travis.gofmt.sh # Format code
  - docker-compose up --build -d # Run application, tests...
