# .travis.yml
language: go

services:
  - docker

sudo: false

# Test for different go environemets
go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

before_install:
  # Let's stop postgresql
  - sudo service postgresql stop
  - sudo service mysql stop
  # wait for mysql to shutdown
  - while sudo lsof -Pi :3306 -sTCP:LISTEN -t; do sleep 1; done

install:
  - docker-compose up --build -d # Run application, tests...

before_script:
  - chmod +x ./.travis.gofmt.sh

script:
  - ./.travis.gofmt.sh # Format code
  - docker exec golang_server ./controllers/controllers.test -test.v # Run tests
