version: '3'
services:
  # Golang server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Name of the Image
    container_name: golang-server
    ports:
      - '8080:8000'
    networks:
      - mynet
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql
    container_name: golang-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'golang-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    # TODO sec
    # expose:
      # Opens port 3306 on the container
      # - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      # Bind mount for the config
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mynet
# Docker Networks
networks:
  mynet:
    driver: bridge
# Names our volume
volumes:
  my-db:
